esphome:
  name: bluetoothtemp
  platform: ESP32
  board: mhetesp32devkit


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
#  power_save_mode: none

captive_portal:

web_server:
  port: 80

logger:

# Enable Home Assistant API
api:
  password: !secret wifi_pass
ota:
  password: !secret wifi_pass
  
# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsdcgq 
    mac_address: 58:2D:34:3B:69:6A
    temperature:
      name: "Terrarium temperatuur links"
    humidity:
      name: "Terrarium luchtvochtigheid links"
    battery_level:
      name: "Terrarium battery level links"


  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:9C:C6:D4
    temperature:
      name: "Terrarium temperatuur rechts"
    humidity:
      name: "Terrarium luchtvochtigheid rechts"
    battery_level:
      name: "Terrarium battery level rechts"
    battery_voltage:
      name: "Terrarium battery voltage rechts"
