substitutions:
  device_name: Achtertuin

esphome:
  name: solar_weather

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass


#api:

# Enable logging
logger:


mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass
  birth_message:
  will_message:

ota:
  password: !secret wifi_pass

i2c:
 - id: ic_1
   sda: 21
   scl: 22
   scan: true
   
dallas:
  - pin: GPIO4

binary_sensor:
  - platform: status
    name: ${device_name} Status

sensor:
  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 30s
    
  - platform: dallas
    address: 0x540215726CAEFF28
    name: ${device_name} Temperatuur

  - platform: pulse_counter
    name: "rain_gauge"
    pin:
      number: GPIO25
      mode: INPUT_PULLUP    
    update_interval: 25s
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    unit_of_measurement: "mm"
    icon: "mdi:water"
    filters:
      - multiply: 0.359254458
      
  - platform: pulse_meter
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
    name: '${device_name} Windsnelheidsmeter'
    icon: 'mdi:weather-windy'
    id: wind_meter
    unit_of_measurement: 'm/s'
    accuracy_decimals: 2
    internal_filter: 13us
    timeout: 5s
    filters:
      - multiply: 0.005560619
      - sliding_window_moving_average:
          window_size: 20
          send_every: 20



  - platform: bmp280
    address: 0x76
    temperature:
      name: ${device_name} Interne Temperatuur
      oversampling: 16x
    pressure:
      name: ${device_name} Luchtdruk
      oversampling: 16x
    #humidity:
    #  name: ${device_name} Luchtvochtigheid
    update_interval: 30s

  - platform: bh1750
    name: ${device_name} Lux
    address: 0x23
    update_interval: 30s

  - platform: ltr390
    uv_index:
      name: ${device_name} UV Index
    uv:
      name: ${device_name} UV
    light:
      name: ${device_name} Lux top
    update_interval: 30s

  - platform: adc
    pin: GPIO33
    name: ${device_name} Analogue Batt Value
    id: analog_val
    attenuation: auto
  
deep_sleep:
  run_duration: 40s
  sleep_duration: 4min
  wakeup_pin: 25
  wakeup_pin_mode: INVERT_WAKEUP
  
  