esphome:
  name: watersproeier
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  power_save_mode: none


captive_portal:

# Webserver
web_server:
  port: 80

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: !secret wifi_pass

ota:
  password: !secret wifi_pass

# ESP-01 relay board normally uses GPIO0 
# But GPIO0 "blinks" during boot therefore
# resolderd the board to use GPIO03
switch:
  - platform: gpio
    name: "Terrarium watersproeier"
    restore_mode: ALWAYS_OFF
    pin: GPIO3