
################################################
## Packages / Light living room
################################################
homeassistant:
  customize:
    light.lamp_bank:
      friendly_name: Lamp Bank
    light.lamp_tv:
      friendly_name: Lamp TV  
    switch.momentary_toggle_lights:
      friendly_name: Alle lampen schakelen
      icon: mdi:lightbulb-group-outline
       
################################################
## Light group
################################################    
light:
  - platform: group
    name: Woonkamer lampen
    entities:
      - light.lamp_bank
      - light.lamp_tv

################################################
## Input Boolean
################################################    
input_boolean:
  lampen_ingeschakeld:
    name: Alle lampen schakelen
    icon: mdi:toggle-switch-outline
  lampen_geschakeld_niet_thuis:
    name: Lampen geschakeld niemand thuis 

################################################
## Automation
################################################

automation:    

##############################################
# Switch on living room lights 
##############################################
- alias: "Schakel verlichting woonkamer in"
  id: '500'
  trigger:
    # Tuin licht sensor
    - platform: numeric_state
      id: beetje donker
      entity_id: sensor.achtertuin_lux
      below: 40 
    - platform: numeric_state
      id: donker
      entity_id: sensor.achtertuin_lux
      below: 25
    - platform: numeric_state
      id: heel donker
      entity_id: sensor.achtertuin_lux
      below: 10
    # Woonkamer schakelaaar geschakeld  
    - platform: state
      id: woonkamer schakelaar
      entity_id: sensor.woonkamerschakelaar_click
      to: single
    # tablet schakelaaar geschakeld  
    - platform: state
      id: tablet schakelaar
      entity_id: input_boolean.lampen_ingeschakeld
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.vakantie
      state: "off"
    - condition: or
      conditions:
      - condition: time
        before: "22:00:00"
        after:  "15:00:00"
      - condition: time    
        before: "11:00:00"
        after:  "04:00:00"
  action:
    - choose:
        - conditions:
          # lampen aan bij beetje donker
            - condition: trigger
              id: beetje donker
            - condition: state
              entity_id: group.familie_aanwezig_tracker
              state: "home"            
          sequence:
            - service: light.turn_on
              data:
                brightness_pct: 25
              target:
                entity_id: light.woonkamer_lampen
            - service: input_boolean.turn_on
              entity_id: input_boolean.lampen_ingeschakeld
        # Lampen aan bij donker of via schakelaars       
        - conditions:
          - or:
            - condition: trigger
              id: donker
            - condition: trigger
              id: woonkamer schakelaar
            - condition: trigger
              id: tablet schakelaar
          - and :
            - condition: state
              entity_id: group.familie_aanwezig_tracker
              state: home
          sequence:
            - service: light.turn_on
              data:
                brightness_pct: 50
              target:
                entity_id: light.woonkamer_lampen
            - service: input_boolean.turn_on
              entity_id: input_boolean.lampen_ingeschakeld
        - conditions:
          # lampen aan bij heel donker
            - condition: trigger
              id: heel donker
            - condition: state
              entity_id: group.familie_aanwezig_tracker
              state: "home"    
            - condition: state
              entity_id:
                - sensor.x_mas_active
              state: "False"
          sequence:
            - service: light.turn_on
              data:
                brightness_pct: 75
              target:
                entity_id: light.woonkamer_lampen
            - service: input_boolean.turn_on
              entity_id: input_boolean.lampen_ingeschakeld
        - conditions:
          # Schakel input boolean wanneer niemand thuis is
            - condition: not
              conditions:
                - condition: state
                  entity_id: group.familie_aanwezig_tracker
                  state: "home"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.lampen_geschakeld_niet_thuis              

##############################################
# Switch on living room lights after door open
##############################################
- alias: Schakel woonkamer lampen in na niet thuis te zijn geweest
  id: '502'                
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.voordeur_contact
      to: "on"
    - platform: state
      entity_id:
        - binary_sensor.schuifpui_contact
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.lampen_geschakeld_niet_thuis
      state: "on"
  action:
    - service: light.turn_on
      data:
        brightness: 75
      target:
        entity_id: light.woonkamer_lampen
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.lampen_geschakeld_niet_thuis
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.lampen_ingeschakeld    

##############################################
# Switch off living room lights
##############################################
- alias: Schakel woonkamer lampen uit
  id: '505'
  trigger:
  # Smart swicht on 1e floor  
  - entity_id: sensor.woonkamerschakelaar_click
    platform: state
    to: double
  # Toggle switch on tablet
  - platform: state
    entity_id: input_boolean.lampen_ingeschakeld
    to: "off" 
  # Zonsopkomst 
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 8 
  # Tuin licht sensor  
  - platform: numeric_state
    entity_id: sensor.achtertuin_lux
    above: 40 
  condition:
    condition: and
    conditions: 
    - condition: state
      entity_id: input_boolean.vakantie
      state: "off"  
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.woonkamer_lampen
    - service: input_boolean.turn_off
      entity_id: input_boolean.lampen_ingeschakeld
    - service: input_boolean.turn_off
      entity_id: input_boolean.lampen_geschakeld_niet_thuis