################################################
## Packages / Low level battery check
################################################
homeassistant:




################################################
## Automation
################################################

automation:

- alias: Low battery level detection & notification for all battery sensors
  id: '700'
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 20
      time: '16:00:00'
      day: 0
      exclude:
        entity_id:
        - sensor.body_battery_charged
        - sensor.body_battery_drained
        - sensor.body_battery_highest
        - sensor.body_battery_lowest
        - sensor.body_battery_most_recent
        device_id:
      actions:
      - service: notify.sander
        data:
          message: Batterij niveau te laag van {{sensors|replace("_"," ")}}
