################################################
## Template
################################################
template:
  

################################################
## Utility meter 
################################################
utility_meter:
  pv_emonth:
    source: sensor.today_s_pv_generation
    cycle: monthly

  pv_eday:
    source: sensor.today_s_pv_generation
    cycle: daily
################################################
## Automation
################################################

################################################
## Sensor
################################################
sensor:

- platform: template
  sensors:
    pv_actual:
      friendly_name: "Actuele zonne-energie"
      unit_of_measurement: W
      value_template: >-
        {% if is_state('sensor.pv_power' , 'unavailable')  %}
          0.0
        {% else %}
          {{ states('sensor.pv_power') }}
        {% endif %}

    pv_today:
      friendly_name: "Dagelijks Zonne-energie opbrengst"
      unit_of_measurement: kWh
      icon_template: mdi:solar-power-variant
      value_template: >-
        {% if is_state('sensor.today_s_pv_generation' , 'unavailable')  %}
          {{ states('sensor.pv_eday') }}
        {% else %}
          {{ states('sensor.today_s_pv_generation') }}
        {% endif %}