################################################
## Packages / Raspberry Pi data
################################################
homeassistant:


################################################
## Sensor
################################################
sensor:

  - platform: systemmonitor
    resources:
    - type: processor_use
    - type: disk_use_percent
      arg: "/"
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_temperature
    - type: last_boot  
    - type: load_1m
    - type: load_5m
    - type: load_15m

