################################################
## Packages / X-mas
################################################
homeassistant:


################################################
## Sensor
################################################
  
template:
  - sensor:
        - name: "X-mas Active"
          state: >
            {% set n = now() %}
            {% if ( n.month >= 12 and ( n.day >= 5 )) or ( n.month == 1 and ( 1 <= n.day <= 6 )) %} 
            True
            {% else %}
            False
            {% endif %}
            
################################################
## Input Boolean
################################################    
input_boolean:
  kerstlampen_ingeschakeld:
    name: Kerstlampen ingeschakeld
    icon: mdi:toggle-switch-outline 

################################################
## Automation
################################################

automation:    
###### Schakel kerstverlichting in ######
- alias: Schakel kerstverlichting in
  id: '1501'
  trigger:
    - platform: numeric_state
      entity_id: sensor.achtertuin_lux
      below: 15
    - entity_id: sensor.woonkamerschakelaar_click
      platform: state
      to: single
    - platform: state
      entity_id: switch.momentary_toggle_lights
      to: "on"
  condition:
    condition: and
    conditions:     
    - condition: time
    # At least one of the following is required.
      before: '22:00:00'
    - condition: state 
      entity_id: sensor.x_mas_active
      state: "True"
    - condition: state 
      entity_id: input_boolean.kerstlampen_ingeschakeld
      state: "off"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.wcd_bank
          - light.wcd_tv
          - light.wcd_kerstverlichting_3
          - light.wcd_kerstverlichting_4
    - service: input_boolean.turn_on
      entity_id: input_boolean.kerstlampen_ingeschakeld
    - delay: 
        seconds: 2
#    - service: light.turn_off
#      entity_id:
#      - light.lampbank_light
      
          
##############################################

###### Schakel kerstverlichting uit ######
- alias: Schakel kerst verlichting uit
  id: '1500'
  trigger:
  # Smart drukknop op 1e verdieping  
  - entity_id: sensor.woonkamerschakelaar_click
    platform: state
    to: double
  # Toggle switch op table
  - platform: state
    entity_id: switch.momentary_toggle_lights
    to: "on"
  # Zonsopkomst 
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 8 
  # Tuin licht sensor  
  - platform: numeric_state
    entity_id: sensor.achtertuin_lux
    above: 30
  condition:
    - condition: state 
      entity_id: sensor.x_mas_active
      state: "True"  
    - condition: state
      entity_id: input_boolean.kerstlampen_ingeschakeld
      state: "on" 
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - light.wcd_bank
          - light.wcd_tv
          - light.wcd_kerstverlichting_3
          - light.wcd_kerstverlichting_4
    - service: input_boolean.turn_off
      entity_id: input_boolean.kerstlampen_ingeschakeld
##############################################
